databases:
  - name: booklist
    databaseName: matthew_week2
    user: ltvuser
    plan: free

services:
  - type: web
    name: booklist
    runtime: ruby
    plan: free
    buildCommand: "chmod +x ./bin/rails && chmod +x ./bin/render-build.sh && ./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booklist
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false